name: 04-Workflow Events

on: 
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: new-code/github_projects/.github/04-github-action

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Debug directory structure
      - name: Debug directory structure
        run: |
          echo "Current working directory:"
          pwd
          echo "Listing all files and directories:"
          ls -R

      # Step 3: Run script with Bash
      - name: Run Bash script
        shell: bash
        run: ./script.sh

      # Step 4: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Step 5: Install Dependencies
      - name: Install Dependencies
        run: npm ci

      # Step 6: Run Tests
      - name: Run Tests
        run: npm run test
