name: 04-Workflow Events
on: 
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /Users/uzoma/new-code/github_projects/.github/04-github-action
    steps:
      - name: checkout code
        uses: action/checkout@v4
      - name: Printing folder
        run: ls
       
      - name: setup node
        uses: action/setup-node@v3
        with:
          node-version: '20.x'
      - name: install Dependencies
        run: npm ci
      - name: run test
        run: npm run test
