name: 01-Building Blocks
on: push
jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "Hello, Worlds"
  echo-Passed:
    runs-on: ubuntu-latest
    steps:
      - name: sucess code
        run: |
            echo "sucess code"
            exit 0
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: say goodbye
        run: echo "goodbye"
     